spring.application.name=study-companion
spring.datasource.url=jdbc:postgresql://localhost:5432/studycompanion
spring.datasource.username=turkan
spring.datasource.password=devpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true